### ISSUE TITLE
Add readme to the master branch

### ISSUE THREAD

**Issue by Defman21** [eOS-themes/eXGTK#19]
I'm from Russia and my English ain't so perfect so @crutchcorn please do that after the source will be cleaned.

**Comment by crutchcorn** [comment]
I did it! ;P Hehe. Will improve when the source is cleaned

**Comment by Defman21** [comment]
Ah, okay! I didn't see that :smiley:

**Comment by Defman21** [comment]
The source is cleaned. Improve the readme if you want :+1:

**Comment by crutchcorn** [comment]
Will do
