### ISSUE TITLE
Rename the theme

### ISSUE THREAD

**Issue by Defman21** [eOS-themes/eXGTK#23]
I think we should re-name the theme.

**Comment by crutchcorn** [comment]
I agree, however I made this theme for a really crappy joke setup, and by god - I will make said really crappy joke before we retire the name. Man, I sleep once this week and you finish the theme. Thanks

**Comment by Defman21** [comment]
Now we should think of a name for the theme.

**Comment by Defman21** [comment]
It can be eOselmite :smile:

**Comment by crutchcorn** [comment]
Can I still make that really crappy joke?

**Comment by Defman21** [comment]
Not sure I understand you right. What do you mean in "crappy joke"?

**Comment by crutchcorn** [comment]
goo.gl/cC2KoX

**Comment by crutchcorn** [comment]
There. Crappy joke made. Commence with renaming

**Comment by Defman21** [comment]
Hahaha :smile:

**Comment by crutchcorn** [comment]
I personally think it shouldn't start with an e at all. My original reason for EX GTK was because there is a pokemon type called EX but I couldn't find it on that card making website. Anyway, putting e at the start is kinda tacky

**Comment by Defman21** [comment]
It can be EXGTK, why not.

**Comment by crutchcorn** [comment]
Lol. Wut? I think it's silly and immature of me. (which at the time I was doing for myself so I didn't care)

**Comment by Defman21** [comment]
So it shouldn't start with an "e" symbol (e/E)... That's hard. Maybe we can join parts of some words to get a good name for the theme.

**Comment by crutchcorn** [comment]
I like the sound of that plan. What about instead of Yosemite, we call it OSX something? ElementX? IDK...

**Comment by crutchcorn** [comment]
Dislike the suggestion exOS as 
1) We're not an OS 
2) No more ex. That was me being stupid.

**Comment by vinctux** [comment]
exOS was just though as an anagram - "X OS" for "OS X". The "e" was meant for elementary.
How about Xenite? A combo of xenon, the noble gas, and Yosemite. As xenon this theme should represent something noble.

**Comment by Defman21** [comment]
Why this so hard?! :disappointed:

**Comment by Defman21** [comment]
Xenite is a good idea.

**Comment by crutchcorn** [comment]
Xenite isn't too bad TBH

**Comment by Defman21** [comment]
Let's stop on "Xenite". I like it
