### ISSUE TITLE
Photos footer has weird borders

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#31]
elementary:
![1](https://cloud.githubusercontent.com/assets/7373586/7279973/51a6f808-e928-11e4-822d-f2b09d1dc519.png)

eXGTK:
![2](https://cloud.githubusercontent.com/assets/7373586/7279976/578b19f2-e928-11e4-98a7-8b88e1b19e45.png)

**Comment by Defman21** [comment]
Should be fixed. Please check it.

**Comment by TicTac7x** [comment]
Fixed.
