### ISSUE TITLE
Improve Wingpanel style, when window maximized

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#32]
![ekraanipilt 2015-04-22 19 49 57](https://cloud.githubusercontent.com/assets/7373586/7280025/d0dc1a36-e928-11e4-8ef4-e2d872a914e0.png)

**Comment by TicTac7x** [comment]
You can also see from the picure that maximized windows still have rounded corners, which is a bug.

**Comment by Defman21** [comment]
Duplicate of #1

**Comment by TicTac7x** [comment]
What about the rounded corners of the maximized window?

**Comment by Defman21** [comment]
Cannot say anything about it. I'm waiting for an answer on reddit.
