### ISSUE TITLE
Sidepanel active label looks weird, in the focused and also in the unfocused window.

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#33]
![ekraanipilt 2015-04-22 19 52 53](https://cloud.githubusercontent.com/assets/7373586/7280102/4bf096d4-e929-11e4-905d-8b1338e09799.png)
![ekraanipilt 2015-04-22 19 52 02](https://cloud.githubusercontent.com/assets/7373586/7280105/4e75a76e-e929-11e4-8bab-dbebb25d8514.png)

**Comment by Defman21** [comment]
Fixed locally. Will push the fix now.
