### ISSUE TITLE
Wingpanel "Apps" pressed button looks ugly

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#34]
![ekraanipilt 2015-04-22 19 55 02](https://cloud.githubusercontent.com/assets/7373586/7280180/c7030fbe-e929-11e4-94fc-461462aa8e96.png)

Note: elementary uses transparent, just they way it is without being pressed, maybe use that also.

**Comment by Defman21** [comment]
Also fixed for the Calendar button in Wingpanel.

**Comment by TicTac7x** [comment]
Fixed for apps and calendar, but maybe the indicators should use this as well?

**Comment by Defman21** [comment]
I don't think so. @crutchcorn how do you feel about it?

**Comment by crutchcorn** [comment]
What does it look like now?

**Comment by Defman21** [comment]
![scr](https://cloud.githubusercontent.com/assets/7373586/7280180/c7030fbe-e929-11e4-94fc-461462aa8e96.png) but for apps icons in the panel

**Comment by crutchcorn** [comment]
I think it should be that way simply because the icons are very close together

**Comment by TicTac7x** [comment]
elementary theme uses no background as well and it looks very nice. If the apps and calendar don't have the background and then the indicators do, it looks out of place.
