### ISSUE TITLE
Slingshot search bar should look the same like in the other windows, or opposite way to make it look unified

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#35]
![search1](https://cloud.githubusercontent.com/assets/7373586/7280330/8be18a4a-e92a-11e4-9e0a-67ec6d1418ce.png)
![search2](https://cloud.githubusercontent.com/assets/7373586/7280333/8e48d8d8-e92a-11e4-8e64-917e52462961.png)

**Comment by Defman21** [comment]
Application name?

**Comment by Defman21** [comment]
Nwm, reproduced.

**Comment by Defman21** [comment]
Ohh, I won't do that, sorry. It looks ugly if I copy the style from Applications or from Pantheon-Files "breadcrumbs" input.

**Comment by TicTac7x** [comment]
At least make it look sharper?

**Comment by Defman21** [comment]
Sharper where? In Applications or in Pantheon-Files?

**Comment by TicTac7x** [comment]
In Slingshot

**Comment by Defman21** [comment]
But it looks good with the buttons before the search-bar, isn't it?

**Comment by Defman21** [comment]
I can remove the blue inset shadow but I wouldn't make the search-bar sharper.

**Comment by TicTac7x** [comment]
I guess that the shadow is what makes it look different from rest of the theme, or maybe change the color? Not sure what would look more unified with the rest of the theme.

**Comment by Defman21** [comment]
It should looks fine now.
