### ISSUE TITLE
eXGTK theme overrides Pantheon's Plank theme, should not use the "default" black one

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#37]

**Comment by Defman21** [comment]
Will be used LightPanel theme.

**Comment by crutchcorn** [comment]
@Defman21, link to said theme?

**Comment by Defman21** [comment]
https://github.com/rhoconlinux/plank-themer/tree/master/themes-proposed/Elementary_Update/LightPanel

**Comment by Defman21** [comment]
Here's it! https://github.com/eOS-themes/eXGTK/commit/8ac03c0f062c97a5cae6774af8c9ab339cce6385
