### ISSUE TITLE
Slingshot apps pages buttons are brighter than the other Slingshot text

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#38]
![pages](https://cloud.githubusercontent.com/assets/7373586/7282694/58b5c0ea-e93a-11e4-8c54-8c44d7f952b9.png)

**Comment by Defman21** [comment]
Here's a big problem. I don't know why but by some reasons slingshot becomes "unfocused" even if it focused. I cannot debug the "focused" slingshot so here's a bug with focused slingshot page changer buttons: if you press on them, they will become darker but text won't change to white.
