### ISSUE TITLE
Slingshot border has weird 1px transparent innerborder

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#39]
![ekraanipilt 2015-04-22 21 54 19](https://cloud.githubusercontent.com/assets/7373586/7282731/9a3831f6-e93a-11e4-825e-6604afb835f4.png)

**Comment by Defman21** [comment]
Very hard to see. Not important but I'll fix that.

**Comment by TicTac7x** [comment]
You can see it here, looks very ugly:
![ekraanipilt 2015-04-22 22 03 53](https://cloud.githubusercontent.com/assets/7373586/7282887/8c9f4970-e93b-11e4-81b9-85160bb20b68.png)

**Comment by Defman21** [comment]
Fixed. Now it uses box-shadow with inset property instead of a border.
