### ISSUE TITLE
Slingshot active categories view looks ugly

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#41]
a) make the color the same as the text
b) change background of the active view, like in elementary theme
* Same applies for the border color of the search bar?

![ekraanipilt 2015-04-22 22 05 47](https://cloud.githubusercontent.com/assets/7373586/7282974/0a0817b6-e93c-11e4-8914-17dd5c5bbe75.png)
![ekraanipilt 2015-04-22 22 05 21](https://cloud.githubusercontent.com/assets/7373586/7282976/0d02670a-e93c-11e4-995b-69c9c877d81e.png)

**Comment by TicTac7x** [comment]
Looks like the new color of the borders look too dark. Use the color of the Slingshots' outer-border instead, the little bit brighter one.

**Comment by TicTac7x** [comment]
The color is still wrong, maybe use #bfbfbf instead?

**Comment by Defman21** [comment]
That ain't a very critical now. I'll play around with the colors but not now.
