### ISSUE TITLE
Style of the info of the file in Pantheon Files is ugly

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#42]
![ekraanipilt 2015-04-22 22 19 30](https://cloud.githubusercontent.com/assets/7373586/7283282/2895a8a4-e93e-11e4-846b-cec43cfe94ed.png)
![ekraanipilt 2015-04-22 22 19 16](https://cloud.githubusercontent.com/assets/7373586/7283284/2bb9e4aa-e93e-11e4-9a95-308dd6256b8e.png)

**Comment by crutchcorn** [comment]
The bottom one?

**Comment by Defman21** [comment]
Yep. Will fix.

**Comment by TicTac7x** [comment]
Top one is eXGTK, bottom elementary.
