### ISSUE TITLE
Unfocused window bars look ugly compared to the focused ones

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#43]
I guess the dark borders in the unfocused windows make it look bad, focused window buttons don't have any sort of border at all.
Focused:
![ekraanipilt 2015-04-22 22 23 45](https://cloud.githubusercontent.com/assets/7373586/7283380/d090ea5a-e93e-11e4-8800-697eab3d0edd.png)

Unfocused:
![ekraanipilt 2015-04-22 22 24 10](https://cloud.githubusercontent.com/assets/7373586/7283383/d83ede1a-e93e-11e4-805c-16279df9dc41.png)

**Comment by Defman21** [comment]
Reproduced, thanks.

**Comment by TicTac7x** [comment]
No problem :)

**Comment by TicTac7x** [comment]
The focused window button look worse now:
![ekraanipilt 2015-04-22 23 42 27](https://cloud.githubusercontent.com/assets/7373586/7284904/43f50fc6-e949-11e4-938b-96b696185401.png)

There is also some weird 2px borders in the combo boxes.

**Comment by Defman21** [comment]
I'm still working on it.
>There is also some weird 2px borders in the combo boxes.

Screen?

>Also what about showing the breadcrumb borders?

Something I will do.

**Comment by TicTac7x** [comment]
In the unfocused window don't the button borders look too dark? Or maybe maybe the icons in the breadcrumb brighter and don't change the borders' color.
![ekraanipilt 2015-04-22 23 44 46](https://cloud.githubusercontent.com/assets/7373586/7284956/b285ce9e-e949-11e4-9b0a-55ca7d88c7e3.png)

**Comment by Defman21** [comment]
A commit broke it. Will fix.

**Comment by Defman21** [comment]
Please create a new issue if you find something broken in the Pantheon tabs
