### ISSUE TITLE
Do not use boxes around close, maximize and minimize

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#44]
![ekraanipilt 2015-04-22 22 31 50](https://cloud.githubusercontent.com/assets/7373586/7283465/78cdeb14-e93f-11e4-80c6-f2154c4f79cc.png)

**Comment by TicTac7x** [comment]
Note: The unclickable button has also the box around, I think i already filed a seperate issue for that

**Comment by Defman21** [comment]
I cannot reproduce to that.
![scr](http://i.imgur.com/BYWuVF9.png)

**Comment by TicTac7x** [comment]
Weird, I have this box all the time when selecting the window buttons from the headerbar.

**Comment by Defman21** [comment]
@crutchcorn are you able to reproduce that?

**Comment by TicTac7x** [comment]
It is fixed with some previous update already.
