### ISSUE TITLE
Button borders too dark

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#46]
![ekraanipilt 2015-04-22 22 39 47](https://cloud.githubusercontent.com/assets/7373586/7283631/87cbf830-e940-11e4-846e-19bd54a7ee2a.png)

You can see that in the combo box in the middle the line is brighter, maybe use that instead.

**Comment by Defman21** [comment]
The borders should be visible and the bug is the border between the top buttons.
