### ISSUE TITLE
Make tabs look better

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#47]
![ekraanipilt 2015-04-23 00 26 48](https://cloud.githubusercontent.com/assets/7373586/7285749/8b4544d0-e94f-11e4-82df-38e0e9493b7d.png)

Tabs left/right borders should be the same color as the upper tab's bar border color. Tabs bar should also have a bottom border, also same color.

**Comment by Defman21** [comment]
There's no top-border for tabs :\

**Comment by TicTac7x** [comment]
Change the color of the seperators to #cacaca.
