### ISSUE TITLE
Not-so-nice content dialogs

### ISSUE THREAD

**Issue by vinctux** [eOS-themes/eXGTK#51]
Hi,
I really enjoy this beautiful theme (especially the OSX-like window buttons), but it's kind of full of small and also big holes.

The dialogs (so the non-main windows of an app) are presented like this - http://imgbox.com/r9gtns4W. The buttons, tabs, fields, boxes, all there is like in an old Windows config, I guess? (I'm not a graphic expert).

Is there any way that this could be fixed?

Thanks for awesome theme,
vinctux

**Comment by Defman21** [comment]
Please install gtk2-engines-pixbuf.

**Comment by Defman21** [comment]
Also @crutchcorn we definitely must include this info to README.

**Comment by crutchcorn** [comment]
For sure. Although IDK why it's not installed for some but is for others

**Comment by Defman21** [comment]
I dunno too.

**Comment by vinctux** [comment]
Thanks,  ```gtk2-engines-pixbuf``` fixed it :+1:
